# Harlequin configuration file
# Ref: https://harlequin.sh/docs/config-file

default_profile = "dev"

[profiles.dev]
adapter = "postgres"
host = "localhost"
port = 5432
user = "postgres"
password = "password"
dbname = "modern_rails_development"

[profiles.test]
adapter = "postgres"
host = "localhost"
port = 5432
user = "postgres"
password = "password"
dbname = "modern_rails_test"
