# Harlequin configuration file
# Ref: https://harlequin.sh/docs/config-file

default_profile = "dev"

[profiles.dev]
adapter = "sqlite"
conn_str = ["storage/development.sqlite3"]

[profiles.test]
adapter = "sqlite"
conn_str = ["storage/test.sqlite3"]
