encryptionsalt: v1:B/NCUKEAKz0=:v1:7DghXEsuNKsowWlz:hg44G2LTfXXkM1577Emr9fK20JyJqQ==
config:
  gcp:project: modern-rails-1786791154
  gcp:region: us-central1
  gcp:zone: us-central1-a
  modern-rails-infra:machineType: e2-micro
  modern-rails-infra:domain: 'ochans.com'
  cloudflare:apiToken:
    secure: v1:s6jWfx19osCe6SiI:BNyRXO1yQjmuqqCzesl4DHfXgrM36WzQLr3kCwVZBieP5k+GUb2rG0hSHfNmoMERDaFVBcdti8CgJROwz1h96JLyYx2d
  modern-rails-infra:cloudflareZoneId: 1f851618f5cd4053301cee5eb4f728eb
