class OrdersController < ApplicationController
  before_action :set_order, only: %i[show complete receipt]

  def my
    @orders = current_user.orders.recent.includes(order_items: :product)
  end

  def show
    unless current_user.admin? || @order.user_id == current_user.id
      redirect_to mypage_orders_path, alert: "アクセス権限がありません。"
    end
  end

  def complete
    unless current_user.admin? || @order.user_id == current_user.id
      redirect_to mypage_orders_path, alert: "アクセス権限がありません。"
    end
  end

  def create
    @cart = current_cart
    items = @cart.items

    if items.empty?
      redirect_to cart_path, alert: "カートに商品がありません。"
      return
    end

    order = nil
    updated_products = []

    ActiveRecord::Base.transaction do
      # 1. Verify stock & Lock products
      total_amount = 0

      items.each do |item|
        product = Product.lock.find(item.product_id)
        if product.stock_quantity < item.quantity
          raise "「#{product.name}」の在庫が不足しています。（残り#{product.stock_quantity}個）"
        end

        # Deduct stock
        product.stock_quantity -= item.quantity
        product.save!
        updated_products << product
        total_amount += (item.price_at_add || product.price) * item.quantity
      end

      # 2. Create Order (Mock Payment -> Paid)
      order = current_user.orders.create!(
        order_number: Order.generate_order_number,
        total_amount: total_amount,
        status: "paid"
      )

      # 3. Create OrderItems
      items.each do |item|
        order.order_items.create!(
          product_id: item.product_id,
          price_at_purchase: item.price_at_add || item.product.price,
          quantity: item.quantity
        )
      end

      # 4. Clear Cart
      @cart.clear
    end

    # 5. Enqueue background jobs
    OrderConfirmationMailJob.perform_later(order.id)
    ReceiptGenerationJob.perform_later(order.id)

    # 6. Realtime broadcasts (Solid Cable / Turbo Streams)
    # A. Broadcast updated stock to product pages
    updated_products.each do |prod|
      prod.purge_catalog_cache
      begin
        Turbo::StreamsChannel.broadcast_replace_to(
          "product_inventory_#{prod.id}",
          target: "product_stock_badge_#{prod.id}",
          partial: "products/stock_badge",
          locals: { product: prod }
        )
      rescue => e
        Rails.logger.warn "Broadcast inventory failed: #{e.message}"
      end
    end

    # B. Broadcast new order to admin dashboard
    begin
      Turbo::StreamsChannel.broadcast_prepend_to(
        "admin_orders",
        target: "recent_orders_list",
        partial: "admin/dashboard/order_row",
        locals: { order: order }
      )
      Turbo::StreamsChannel.broadcast_replace_to(
        "admin_orders",
        target: "dashboard_stats",
        partial: "admin/dashboard/stats_summary"
      )
      Turbo::StreamsChannel.broadcast_append_to(
        "admin_orders",
        target: "toast_container",
        partial: "admin/dashboard/toast",
        locals: { message: "新規注文受付: #{order.order_number} (¥#{order.total_amount})" }
      )
    rescue => e
      Rails.logger.warn "Broadcast admin order failed: #{e.message}"
    end

    redirect_to complete_order_path(order), notice: "ご注文が完了しました！"
  rescue => e
    redirect_to checkout_path, alert: "ご注文の処理中にエラーが発生しました: #{e.message}"
  end

  def receipt
    unless current_user.admin? || @order.user_id == current_user.id
      redirect_to mypage_orders_path, alert: "アクセス権限がありません。"
      return
    end

    if @order.receipt.attached?
      send_data @order.receipt.download,
                filename: "receipt_#{@order.order_number}.pdf",
                type: "application/pdf",
                disposition: "inline"
    else
      # If not yet generated by async job, generate on the fly
      ReceiptGenerationJob.perform_now(@order.id)
      @order.reload
      if @order.receipt.attached?
        send_data @order.receipt.download,
                  filename: "receipt_#{@order.order_number}.pdf",
                  type: "application/pdf",
                  disposition: "inline"
      else
        redirect_to mypage_orders_path, alert: "領収書PDFを生成中です。少々お待ちください。"
      end
    end
  end

  private

  def set_order
    @order = Order.find(params[:id])
  end
end
